title: "Sehaj's Research Hub"
description: "This is my research hub on mindset, yoga, software and more"
category_color_map:
  yoga: "bg-success"
  mindset: "bg-primary"
  HowTo: "bg-warning"
  self-help: "bg-info"
  book: "bg-info"
  default: "bg-secondary"
