title: "Sehaj's Research Hub"
description: "This is my research hub on mindset, yoga, software and more"
category_color_map:
  yoga: "#28a745" # Green
  lifestyle: "#007bff" # Blue
  mindset: "#ffc107" # Yellow
  self-help: "#fd7e14" # Orange

